### ISSUE TITLE
Overlapping of Project Section

### ISSUE THREAD

**Issue by Naveen-g09** [said7388/developer-portfolio#14]
Issue: Overlapping Sections and Text Collision in Portfolio
I hope this message finds you well. I wanted to express my appreciation for the excellent work done on the portfolio. It's evident that a lot of effort and creativity have gone into its development.

However, while exploring the portfolio, I noticed an issue that I believe warrants attention. Specifically, there appears to be a recurring problem with overlapping sections and text collision, particularly noticeable during scrolling.

To maintain the high standard of presentation and user experience, I suggest considering a solution such as implementing a blurred background effect upon scrolling. This could effectively address the issue while adding a subtle aesthetic enhancement.

I believe addressing this matter would further enhance the overall quality and usability of the portfolio. Thank you for your attention to this matter, and I'm looking forward to seeing the continued refinement of your exceptional work

![image](https://github.com/said7388/developer-portfolio/assets/76151123/c011b301-beba-4660-9d97-c4fc6bc66cbf)

**Comment by said7388** [comment]
Sorry to see that. I couldn't find this issue before. However, I did find it without overlapping.
![image](https://github.com/said7388/developer-portfolio/assets/77630868/a2960e21-7a1e-4a22-ae35-9dc53896bb23)

**Comment by Naveen-g09** [comment]
yes, it got resolved on my version.
Maybe it was my browser issue
Thanks for considering and replying
