### ISSUE TITLE
Template of EmailJS for Reference

### ISSUE THREAD

**Issue by Naveen-g09** [said7388/developer-portfolio#15]
Can you provide an overview of what template should look like in emailjs, because right now i am only getting message content rather than user name, email and message too

The template content should be to resolve this (could you add this to readme):

```
Hello,

You got a new message from {{name}}:

 

Email Id : {{email}}

{{message}}



```

if you are allowing contributors, I can update the readme with step by step images to configure emailJS section. Thanks

**Comment by said7388** [comment]
I'm using this template.
```
Hello, Abu said!

You got a new message from {{name}} via your portfolio website:

{{message}}

Best wishes,
{{name}}
```

**Comment by Naveen-g09** [comment]
Great, Please add those steps in the readme for beginners.
overall a great work man
