### ISSUE TITLE
How to Build?

### ISSUE THREAD

**Issue by Lucia361** [said7388/developer-portfolio#19]
How to host this site? I tried `npm run build` but did not get any static site files so I can directly host into my hosting account.

**Comment by said7388** [comment]
First, run `npm install` to install dependencies then try to build using the `npm run build` command.

**Comment by Lucia361** [comment]
I tried but no dist folder got created. I didn't get the static files anywhere.

**Comment by Lucia361** [comment]
Can you try and please help ne?

**Comment by Lucia361** [comment]
any guide for Vercel ??

**Comment by ErAdilrasheed** [comment]
> any guide for Vercel ??

yes contact me on whatsapp +919616316925
