### ISSUE TITLE
Error Npm run Build

### ISSUE THREAD

**Issue by thiagolopes-dev** [said7388/developer-portfolio#21]
I am using the npm run build command to build the dist folder, as indicated in another edition by you, and it has this output and does not generate any build folder. What can it be?  
  ________________________________________________
  Creating an optimized production build ...
 ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Compiler server unexpectedly exited with code: null and signal: SIGTERM
 ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Compiler client unexpectedly exited with code: null and signal: SIGTERM
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
 ✓ Generating static pages (6/6) 
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    89.2 kB         180 kB
├ ○ /_not-found                          882 B          85.2 kB
├ ○ /blog                                174 B          91.3 kB
└ λ /blog/[slug]                         137 B          84.4 kB
+ First Load JS shared by all            84.3 kB
  ├ chunks/69-78639f94a16fe813.js        29 kB
  ├ chunks/fd9d1056-40aa7d73374bf23f.js  53.4 kB
  └ other shared chunks (total)          1.91 kB

○  (Static)   prerendered as static content
λ  (Dynamic)  server-rendered on demand using Node.js

-----------------------------------------------

And congratulations on the work, I mentioned the credits to you in my repository.

**Comment by said7388** [comment]
By default, Next.js does not generate a traditional "build" folder like some other frameworks. Instead, it generates a ".next" folder.

**Comment by thiagolopes-dev** [comment]
I got it, thanks
