### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by vanloc1808** [said7388/developer-portfolio#34]
Dear Said,
Thank you for a fascinating template.
I have one question, how to change this favicon?
I tried to replace `favicon.ico` with my file, but it does not work 
![image](https://github.com/said7388/developer-portfolio/assets/76842571/2ddca4e8-e9cd-49df-be45-e30818635cb3)

**Comment by akhil11sharma** [comment]
same issue persists in mine also even after replacing favicon image

**Comment by parthamk** [comment]
> Dear Said, Thank you for a fascinating template. I have one question, how to change this favicon? I tried to replace `favicon.ico` with my file, but it does not work ![image](https://private-user-images.githubusercontent.com/76842571/346286657-2ddca4e8-e9cd-49df-be45-e30818635cb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDIzNTcsIm5iZiI6MTcyMDY0MjA1NywicGF0aCI6Ii83Njg0MjU3MS8zNDYyODY2NTctMmRkY2E0ZTgtZTljZC00OWRmLWJlNDUtZTMwODE4NjM1Y2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDIwMDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNjM4ZjI0OGEwMTFhNjhhNzViODE4YmJhMTIyMzZlYzRiMDM0ZDljZDRlN2YzMzhiZDMyMDA1MmUwNTcyN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xhYu3cBAUh8BYdarr5V9ywlKmO4wtGboOVyLIHcUq60)

- [ ] First go inside /public and paste your desired image
- [ ] Then inside /utils/data/personal-data.js change the name of the image

```
export const personalData = {
          [*Other Variable*]
          profile: '/profile.png', ((Change the image name of your desired favicon picture))
          [*Other variable*]
}
```

> Let me know if this solution works.

**Comment by vanloc1808** [comment]
@parthamk No, this is about the profile image
I mean the icon on title bar (the favicon)

**Comment by vanloc1808** [comment]
Issue does not happen anymore, maybe because of cache
@akhil11sharma I tried again after several days and it works :D

**Comment by parthamk** [comment]
> Issue does not happen anymore, maybe because of cache @akhil11sharma I tried again after several days and it works :D

Cool, good to know.
