### ISSUE TITLE
Contact form details send problem

### ISSUE THREAD

**Issue by saiful7778** [said7388/developer-portfolio#8]
I thick you have to update your contact form.

I face this problem
![Screenshot 2024-03-09 at 03-15-22 Portfolio of Abu Said](https://github.com/said7388/developer-portfolio/assets/83330293/10ab4233-d3e5-4ffe-9bd6-a4df3e54819f)
![Screenshot 2024-03-09 at 03-17-49 Portfolio of Abu Said](https://github.com/said7388/developer-portfolio/assets/83330293/c7bb581d-4a5a-47c6-b228-fd9308311e1d)

**Comment by aks057** [comment]
Can u help me, i am facing the same problem, please give a walkthrough about contact page
